# -*- coding: utf-8 -*-
"""preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaSpnS0yAFgF7KE5BQfPdzouv_7m4E6n
"""

script_code = """
import pandas as pd
import numpy as np
import time
from datetime import datetime
from google_play_scraper import reviews, Sort
from langdetect import detect, LangDetectException

# App dictionary
apps = {
    'CBE': 'com.combanketh.mobilebanking',
    'BOA': 'com.boa.boaMobileBanking',
    'Dashen': 'com.dashen.dashensuperapp'
}

def scrape_reviews(apps, max_reviews=1000):
    all_reviews = []

    for bank, app_id in apps.items():
        print(f"\\nScraping reviews for {bank}...")
        result = []
        batch_count = 0
        MAX_BATCHES = 10
        BATCH_SIZE = 200

        try:
            partial, continuation_token = reviews(
                app_id,
                lang='en',
                country='et',
                sort=Sort.NEWEST,
                count=BATCH_SIZE
            )
            result.extend(partial)
            batch_count += 1
            print(f"Batch {batch_count}: Fetched {len(result)} reviews.")

            while len(result) < max_reviews and continuation_token and batch_count < MAX_BATCHES:
                more, continuation_token = reviews(
                    app_id,
                    continuation_token=continuation_token,
                    lang='en',
                    country='et'
                )
                result.extend(more)
                batch_count += 1
                print(f"Batch {batch_count}: Fetched {len(result)} reviews so far.")
                time.sleep(1.5)

            for r in result[:max_reviews]:
                r['bank'] = bank
            all_reviews.extend(result[:max_reviews])

        except Exception as e:
            print(f"Error scraping {bank}: {e}. Using dummy reviews.")
            dummy = [{
                'content': f"Sample review {i} for {bank}",
                'score': np.random.randint(1, 6),
                'at': datetime.now(),
                'bank': bank
            } for i in range(max_reviews)]
            all_reviews.extend(dummy)

    return pd.DataFrame(all_reviews)

def is_latin(text):
    text_alpha = ''.join([c for c in text if c.isalpha()])
    return len(text_alpha) / (len(text) + 1e-5) > 0.7

def is_english(text):
    try:
        return detect(text) == 'en'
    except LangDetectException:
        return False

def clean_reviews(df_raw):
    df = df_raw[['content', 'score', 'at', 'bank']].copy()
    df.columns = ['review', 'rating', 'date', 'bank']
    df['source'] = 'Google Play'

    print(f"Initial review count: {len(df)}")
    df['date'] = pd.to_datetime(df['date']).dt.date

    df.drop_duplicates(subset=['review', 'bank'], inplace=True)
    print(f"After removing duplicates: {len(df)}")

    df.dropna(subset=['review'], inplace=True)
    print(f"After dropping nulls: {len(df)}")

    df = df[df['review'].apply(is_latin)]
    print(f"After filtering non-Latin: {len(df)}")

    df = df[df['review'].apply(is_english)]
    print(f"After filtering non-English: {len(df)}")

    return df.reset_index(drop=True)

if __name__ == "__main__":
    raw_df = scrape_reviews(apps, max_reviews=1000)
    df = clean_reviews(raw_df)
    df.to_csv("bank_reviews_clean.csv", index=False)
    print(f"Cleaned dataset saved. Total reviews: {len(df)}")
"""

with open("preprocessing.py", "w") as f:
    f.write(script_code)

!cat preprocessing.py